paths:
    /missions:
        post:
            summary: '미션 추가'
            parameters:
                - in: body
                  name: 'mission'
                  required: true
                  schema:
                      $ref: '#/definitions/Mission'
            responses:
                '200':
                    description: '미션 추가 성공!'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: 'success!'
                            result:
                                type: object
                                example:
                                    {
                                        'target_amount': 10000,
                                        'reward': 500,
                                        'deadline': 2023-12-01,
                                        'store_name': '가게 이름',
                                    }
                '400':
                    description: '미션 정보 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON001'
                            message:
                                type: string
                                example: '잘못된 요청입니다.'
                '404':
                    description: '등록되지 않은 가게'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON005'
                            message:
                                type: string
                                example: '요청한 페이지를 찾을 수 없습니다. 관리자에게 문의 바랍니다.'
                '500':
                    description: '서버 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON000'
                            message:
                                type: string
                                example: '서버 에러, 관리자에게 문의 바랍니다.'
    /missions/{missionId}:
        post:
            summary: '미션 도전'
            parameters:
                - in: path
                  name: missionId
                  required: true
                  type: integer
            responses:
                '200':
                    description: '미션 도전!'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: 'success!'
                            result:
                                type: object
                                example:
                                    {
                                        'user_name': '홍길동',
                                        'store_name': '가게 이름',
                                        'target_amount': 10000,
                                        'reward': 500,
                                        'deadline': 2023-12-01,
                                        'status': 0,
                                    }
                '400':
                    description: '미션 정보 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON001'
                            message:
                                type: string
                                example: '잘못된 요청입니다.'
                '404':
                    description: '등록되지 않은 미션'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON005'
                            message:
                                type: string
                                example: '요청한 페이지를 찾을 수 없습니다. 관리자에게 문의 바랍니다.'
                '409':
                    description: '이미 도전 중인 미션'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON006'
                            message:
                                type: string
                                example: '중복된 항목입니다.'
                '500':
                    description: '서버 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON000'
                            message:
                                type: string
                                example: '서버 에러, 관리자에게 문의 바랍니다.'
    /missions/stores/{storeId}:
        get:
            summary: '가게 미션 조회'
            parameters:
                - in: path
                  name: storeId
                  required: true
                  type: integer
                - in: query
                  name: missionId
                  required: false
                  type: integer
                - in: query
                  name: limit
                  required: false
                  type: integer
            responses:
                '200':
                    description: '미션 조회 성공'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: 'success!'
                            result:
                                type: object
                                example:
                                    [
                                        { 'reward': 500, 'store_name': '가게 1', 'target_amount': 10000 },
                                        { 'reward': 1000, 'store_name': '가게 2', 'target_amount': 15000 },
                                        { 'reward': 500, 'store_name': '가게 3', 'target_amount': 15000 },
                                    ]
                '500':
                    description: '서버 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON000'
                            message:
                                type: string
                                example: '서버 에러, 관리자에게 문의 바랍니다.'
definitions:
    Mission:
        properties:
            store_id:
                type: integer
                example: 1
            target_amount:
                type: integer
                example: 10000
            reward:
                type: integer
                example: 500
            deadline:
                type: string
                format: date
                example: 2023-12-01
        required:
            - store_id
            - target_amount
            - reward
            - deadline
