paths:
    /reviews:
        post:
            summary: '리뷰 추가'
            parameters:
                - in: body
                  name: 'review'
                  required: true
                  schema:
                      $ref: '#/definitions/Review'
            responses:
                '200':
                    description: '리뷰 추가 성공!'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: 'success!'
                            result:
                                type: object
                                example:
                                    {
                                        'user_name': '홍길동',
                                        'store_name': '가게 이름',
                                        'rating': 5,
                                        'content': '맛있어요!',
                                    }
                '400':
                    description: '리뷰 정보 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON001'
                            message:
                                type: string
                                example: '잘못된 요청입니다.'
                '404':
                    description: '등록되지 않은 가게 또는 미션'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON005'
                            message:
                                type: string
                                example: '요청한 페이지를 찾을 수 없습니다. 관리자에게 문의 바랍니다.'
                '409':
                    description: '이미 작성한 리뷰'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON006'
                            message:
                                type: string
                                example: '중복된 항목입니다.'
                '500':
                    description: '서버 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON000'
                            message:
                                type: string
                                example: '서버 에러, 관리자에게 문의 바랍니다.'
    /reviews/users/{userId}:
        get:
            summary: '리뷰 추가'
            parameters:
                - in: path
                  name: userId
                  required: true
                  type: integer
            responses:
                '200':
                    description: '리뷰 조회 성공!'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: 'success!'
                            result:
                                type: object
                                example:
                                    [
                                        {
                                            'user_name': '홍길동',
                                            'created_at': '2023-12-03T04:10:50.000Z',
                                            'rating': 5,
                                            'content': '맛있어요',
                                        },
                                        {
                                            'user_name': '홍길동',
                                            'created_at': '2023-12-03T04:23:16.000Z',
                                            'rating': 5,
                                            'content': '좋아요',
                                        },
                                    ]
                '500':
                    description: '서버 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON000'
                            message:
                                type: string
                                example: '서버 에러, 관리자에게 문의 바랍니다.'
definitions:
    Review:
        properties:
            store_id:
                type: integer
                example: 1
            mission_id:
                type: integer
                example: 1
            rating:
                type: integer
                example: 5
            content:
                type: string
                example: '맛있어요!'
        required:
            - store_id
            - mission_id
            - rating
