paths:
    /stores:
        post:
            summary: '가게 추가'
            parameters:
                - in: body
                  name: 'store'
                  required: true
                  schema:
                      $ref: '#/definitions/Store'
            responses:
                '200':
                    description: '가게 추가 성공!'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: true
                            code:
                                type: integer
                                example: 2000
                            message:
                                type: string
                                example: 'success!'
                            result:
                                type: object
                                example: { 'store_name': '가게 이름', 'region_name': '청파동' }
                '400':
                    description: '가게 정보 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON001'
                            message:
                                type: string
                                example: '잘못된 요청입니다.'
                '404':
                    description: '등록되지 않은 가게'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON005'
                            message:
                                type: string
                                example: '요청한 페이지를 찾을 수 없습니다. 관리자에게 문의 바랍니다.'
                '500':
                    description: '서버 에러'
                    schema:
                        type: object
                        properties:
                            isSuccess:
                                type: boolean
                                example: false
                            code:
                                type: integer
                                example: 'COMMON000'
                            message:
                                type: string
                                example: '서버 에러, 관리자에게 문의 바랍니다.'
definitions:
    Store:
        properties:
            name:
                type: string
                example: '가게 이름'
            address:
                type: string
                example: '서울특별시 용산구'
            region_id:
                type: integer
                example: 1
        required:
            - name
            - address
            - region_id
